### ISSUE TITLE
get_discovery.py problem

### ISSUE THREAD

**Issue by 7SiebenPunch** [KIT-IAI/eSAX#3]
hi,

i got the subsequence after using get_subsequences.
Then i tried to get the motifs:
Motif = mot.get_motifs (df_ts,subs, breaks=10, word_length=50, num_iterations = 15, mdr = 2.5, cr1 = 5.0, cr2 = 1.5, mask_size=2, seed=42)

Then i got the error:
'list' object has no attribute 'min'

In line: minimum = min([i.min() for i in ts_subs])
![image](https://user-images.githubusercontent.com/101822242/159535569-ffbefaae-64ea-4ccf-a0a3-d42e311c94af.png)

I tried many Time series and I'm using univariate sequence but always have the same error.
Here are the two sequences I used:
![image](https://user-images.githubusercontent.com/101822242/159536164-0a22b19d-db61-4f6d-af2e-609e99552da3.png)
![image](https://user-images.githubusercontent.com/101822242/159536241-8ff16a97-845e-4164-8ac7-bafecc885773.png)

Could you please tell me where I did something wrong?

Looking forward to your reply!

Jiajun

**Comment by JanLuudi** [comment]
Dear Jiajun (@7SiebenPunch),

thank you for using eSAX, and please excuse the late response.

We’ve looked at the error and found out why this is happening. It seems like you gave the whole output of the determine_subsequences() method to the get_motifs() method as ts_subs.
Only the first part (dmin) of the output of the method has to be used, though.
Sorry for the confusing naming of the output! We will update it as soon as possible.

Here is the example for how to call the get_motifs() method properly:

In [15]: motifs = esax.get_motif.get_motifs(ts0, subsequences[0], breaks=10, wor
    ...: d_length=50, num_iterations=15, mdr=2.5, cr1=5.0, cr2=1.5, mask_size=2,
    ...: seed=42)
Creating the eSAX pieces
Searching for Motifs
Done


The output of this method is a dict and looks like this:
found_motifs = {'ts_subs': ts_subs, 'ts_sax_df': ts_sax_df, 'motifs_raw': motifs_raw,
                'motifs_sax': motifs_sax, 'col_mat': col_mat, 'indexes': indexes,
                'pieces_all': pieces_all, 'ecdf': ecdf}

In motifs_raw you find the motifs in numeric representation and in motifs_sax you will find the symbolic aggregation of the subsequences in the motifs.

Best,
Jan

**Comment by 7SiebenPunch** [comment]
Thank you so much!!
